### ISSUE TITLE
[!] No podspec found for `RNImageToPdf` in `../node_modules/react-native-html-to-pdf`

### ISSUE THREAD

**Issue by dharmikvyas** [christopherdro/react-native-html-to-pdf#188]
I am unable to add library in ios, It gives me following error.
```

[!] No podspec found for `RNImageToPdf` in `../node_modules/react-native-html-to-pdf`

Aborting run
An unexpected error was encountered. Please report it as a bug:
Error
    at CocoaPodsPackageManager._installAsync (/Users/apple/.npm/_npx/7336/lib/node_modules/pod-install/build/index.js:2:76001)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by dharmikvyas** [comment]
Oh, Sorry I have tried image to pdf first and than html to pdf and forgot to remove image to pdf so causing error.. No issue now.
